import Head from 'next/head'
import Image from 'next/image'
import { Main } from '@/components/Main/index'
import { Box, Icon, Flex, Heading, Stack, Text, Spinner, UnorderedList, Input, Button, InputProps, ButtonProps } from '@chakra-ui/react'
import { GetServerSideProps } from 'next'
import { api } from '@/services/api'
import { useQuery } from "react-query";
import { HeaderCategoriesPage } from '@/components/CategoriesPage/HeaderCategoriesPage'
import { Card } from '@/components/CategoriesPage/Card'
import { CardContainer } from '@/components/CategoriesPage/CardContainer'
import { useEffect } from 'react'
import { Articles } from '@/components/Articles'
import { Comments } from '@/components/Articles/Comments'
import { api_client } from '@/services/api_client'
import { ArticleCommentsResponse, ArticlesResponse } from './article'



interface ArticlesPageProps {
    slug: string;
    data: ArticlesResponse;
}
export default function ArticlesPage({slug, data: {articles}}: ArticlesPageProps) {  
  const input: InputProps = {
    as:"textarea",
    h:"100px",
    bg:"gray.800",
    p:"2",
    variant:"unstyled"
  }
  const button: ButtonProps = {
    variant:"unstyled",
    px:"6",
    borderRadius:"md",
    bg:"purple.700",
    alignSelf:"flex-start",
    size:"sm"
  }
  const {data, isLoading, isRefetching} = useQuery('comments', async () => {
    const {data} = await api_client.post<ArticleCommentsResponse>("comments/get-article-comments", { slug: articles.slug })
    return {
      comments: data.comments
    }
  })
  return (
    <>
      <Head>
        <title>Artigos | ARTech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main headerComponent={<Articles article={articles}/>}>
        <Stack spacing="4">
           <Heading fontSize="2.25rem" fontWeight="extrabold">
              Comentários
            </Heading> 
            <UnorderedList bg="gray.900" borderRadius="md" m="0" px="4" py="4">
                <Flex as="form" direction="column" py="2">
                    <Input {...input} placeholder='Escreva seu comentário'/>
                    <Button type="submit" {...button}>Enviar</Button>
                </Flex >
                { (isLoading || isRefetching) && <Spinner />}
                {data?.comments && data.comments.map(comment => (
                    <Comments comment={comment}/>
                ))}
            </UnorderedList>
        </Stack>
      </Main>
    </>
  )
}



export const getServerSideProps: GetServerSideProps = async ({req, res, params}) => {
  const slug = params?.slug ?? '';
  
  try {
    const { data } = await api_client.post<ArticlesResponse>("articles/get", { slug: slug })
    
    if(!data.articles) {
        return {
            redirect: {
              destination: '/articles',
              permanent: false
            }
        }
    }
    
    return {
        props: {
            data
        }
    }
  } catch (err) {
    console.log(err);
    return {
        props: {}
    }
  }
  
  
  
}