import Head from 'next/head'
import Image from 'next/image'
import { Main } from '@/components/Main/index'
import { Box, Button, Flex, Heading, Stack, Text } from '@chakra-ui/react'
import { HeaderArticlesPage } from '@/components/ArticlesPage/HeaderArticlesPage'



export default function Articles() {
  return (
    <>
      <Head>
        <title>Artigos | ARTech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main headerComponent={<HeaderArticlesPage />}>
        
      </Main>
    </>
  )
}
