import Head from 'next/head'
import Image from 'next/image'
import { Main } from '@/components/Main/index'
import { Box, Icon, Flex, Heading, Stack, Text, Spinner } from '@chakra-ui/react'
import { GetServerSideProps } from 'next'
import { api } from '@/services/api'
import { useQuery } from "react-query";
import { HeaderCategoriesPage } from '@/components/CategoriesPage/HeaderCategoriesPage'
import { Card } from '@/components/CategoriesPage/Card'
import { CardContainer } from '@/components/CategoriesPage/CardContainer'
import { useEffect } from 'react'

export interface ArticlesResponse {
  slug: string;
  title: string;
  subtitle: string;
  text: string;
  image: string;
  category: string;
  author: string;
  created_at: string;
  state: string;
}

interface CategoriesPageProps {
    category: string;
}
export default function Categories({category}: CategoriesPageProps) {
   

  // TODO: transformar em SSR e criar um Context para isso
  const {data, isRefetching, refetch} = useQuery('articles', async () => {
    const {data} = await api.get<ArticlesResponse[]>("/articles")
    const articles = data.filter(article => article.category === category)
    return articles
  })
  
  useEffect(() => {
    refetch()
  }, [category])  
  return (
    <>
      <Head>
        <title>Artigos | ARTech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main headerComponent={<HeaderCategoriesPage category={category as "front-end"}/>}>
        { isRefetching ? <Spinner /> : 
        <CardContainer articles={data}/>
        }
      </Main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async ({req, res, params}) => {
  const category = params?.category ?? '';

  
  return {
    props: {
        category
    }
  }
}