import Head from 'next/head'
import { Main } from '@/components/Main/index'
import {  Spinner } from '@chakra-ui/react'
import { GetServerSideProps } from 'next'
import { api } from '@/services/api'
import { useQuery } from "react-query";
import { HeaderCategoriesPage } from '@/components/CategoriesPage/HeaderCategoriesPage'
import { Card } from '@/components/CategoriesPage/Card'
import { CardContainer } from '@/components/CategoriesPage/CardContainer'
import { useEffect } from 'react'
import { api_client } from '@/services/api_client'
import { Article, ArticlesResponse } from './category'


interface CategoriesPageProps {
    category: string;
    articles: Article[] | null;
}
export default function Categories({category, articles}: CategoriesPageProps) {
    
  return (
    <>
      <Head>
        <title>{category} | ARTech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Main headerComponent={<HeaderCategoriesPage category={category as "front-end"}/>}>
        
        <CardContainer articles={articles}/>
      </Main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async ({req, res, params}) => {
  const category = params?.category ?? '';

  try {
    const { data } = await api_client.post<ArticlesResponse>("articles/get-by-category", { category })
    
    return {
        props: {
          articles: data.articles.length > 0 ? data.articles : null,
          category
        }
    }
  } catch (err) {
    console.log(err);
    return {
        props: {
          category
        }
    }
  }
}